language: java
 
sudo: false
cache:
  directories:
  - $HOME/.m2
language: java
jdk:
  - openjdk7
env:
  global:
    - SONATYPE_USERNAME=chicchiricco
    - secure: "L/gkTxPXNnTUJ+99fQFZk5tNLLp60DVV0gYvPn5zpWs9kz4rZGHSFppo1X25p62dmTgBAavP1sYVNlcMpgNs20m++aV2daCE925GcfrzkULc9OfJm+AjV4O+B1H+hs/tvQT/PmiHCu+4UUSxXaQAKDesWQ4tuLTAYxBc+p7nzmi5WGhJRIp96a11dgGbVblWR2H2Cgxm5CnLde2Rff6aEWmCPlFvzd2ACNkBL0hHJ4uEJ2D5vpWaX8oFmrRYxx0XwClB2J0neeZz4qSJtPc3VnDONv/RFhw0OvLWRlszCZOyN+CACOTcX8vuT6xTCMYNhxH67nx6I+RpBh1T0UNHYz5XBkE1zVdpbAlM6aYO4mKGHWXZPYOfuPGks02MVxnnRlgc3+CnPlTDBbf0VNwfEvPFiWN1IzyCbnoTyjMv9LquCJ7e6Zo7GTJHpxfM4i9/NORLlrb5GHCSr7w4DEAeKNpBKZp94V0XLQ+cS9J0uZr9sm0xY9v7yqnPX4VB2EYSWtaIF0cwjjR6r71Ua7deX74JcVfhU93i2cww+3togxGHx/MLBcwaEBAhorhjNjT+BfWqHLAvVJ9zcF7IH2C+OckSVKG2iuJbRfOgu1XeYwzRrtGyFz8rEXWrfXyAo38rQi1aIAx9iuLWI3HC5GgkItdM+YaKXHTEH2LgizHPwUA="

after_success:
  - python .travis.addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml

notifications:
  email:
    - connid-dev@googlegroups.com
